version: '2'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    container_name: wordpress
    build:
      context: .wp/
      dockerfile: Dockerfile

    depends_on:
      - db
    tty: true
    ports:
      - "8888:80"
    restart: always
    volumes:
      - ./:/mnt
    environment:
      - WORDPRESS_VERSION
      - WORDPRESS_DB_HOST="db:3306"
      - WORDPRESS_DB_NAME="wordpress"
      - WORDPRESS_DB_USER="wordpress"
      - WORDPRESS_DB_PASSWORD="wordpress"